[package]
name = "smooth-bevy-cameras"
description = "Bevy camera controllers with buttery, exponential smoothing."
version = "0.5.0"
repository = "https://github.com/bonsairobo/smooth-bevy-cameras"
authors = ["Duncan <bonsairobo@gmail.com>"]
keywords = ["bevy", "camera"]
edition = "2021"
license = "MIT"

[dependencies]
bevy = { path = "../bevy", default-features = false, features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_winit", "bevy_gltf", "bevy_render"] }
approx = "0.4"
serde = "1.0"

#[dependencies.bevy]
#version = "0.8"
# git = "https://github.com/bevyengine/bevy"
# rev = "f3de12bc"
# branch = "main"
#default-features = false

#[dev-dependencies.bevy]
# git = "https://github.com/bevyengine/bevy"
# rev = "f3de12bc"
# branch = "main"
#features = ["bevy_asset", "bevy_core_pipeline", "bevy_pbr", "bevy_winit", "bevy_gltf", "bevy_render"]
#default-features = false

#[target.'cfg(target_os = "linux")'.dev-dependencies.bevy]
# git = "https://github.com/bevyengine/bevy"
# rev = "f3de12bc"
# branch = "main"
#features = ["bevy_asset", "x11", "wayland"]
#default-features = false
